title: Epicycle.Graphics (.NET)
url: https://github.com/open-epicycle/Epicycle.Graphics-cs
summary: "Epicycle .NET graphics library. Includes: Platform-independent image library and color infrastructure."

organization: Epicycle
tags: epicycle graphics image bitmap views color ply
copyright: Copyright 2015 Epicycle
license_url: http://www.apache.org/licenses/LICENSE-2.0

release_notes: https://github.com/open-epicycle/Epicycle.Graphics-cs/blob/ver-$version$/README.md

dotnet_frameworks:
 - net35
 - net40
 - net45

nuget_dependencies:
 - Epicycle.Commons-cs.0.1.5.0
 - Epicycle.Math-cs.0.1.3.0

description: |
   Epicycle .NET graphics library. Includes: Platform-independent image library and color infrastructure.
   
   * Details & release notes: https://github.com/open-epicycle/Epicycle.Graphics-cs/blob/ver-$version$/README.md
   * Sources: https://github.com/open-epicycle/Epicycle.Graphics-cs/tree/ver-$version$
   * Git repository: https://github.com/open-epicycle/Epicycle.Graphics-cs